name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      NX_CLOUD_ID: ${{ secrets.NX_CLOUD_ID }}
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ID }}
      NX_CLOUD_ACCESS_KEY: ${{ secrets.NX_CLOUD_ID }}
    steps:
      - name: Log env value
        run: echo "My secret value is $NX_CLOUD_ID"

      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - run: npm ci --legacy-peer-deps

      - run: npx nx run-many -t build

      - run: npx nx run-many -t lint test build

      - run: npx nx-cloud fix-ci
        if: always()
