name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - shell: pwsh
        env:
          NX_CLOUD_ID: ${{ secrets.NX_CLOUD_ID }}
        run: |
          echo "$env:NX_CLOUD_ID"

      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      # Step para verificar se a variável existe
      - name: Check if NX_CLOUD_ID is set
        run: |
          if [ -z "$NX_CLOUD_ID" ]; then
            echo "❌ NX_CLOUD_ID is not set or is empty"
            exit 1
          else
            echo "✅ NX_CLOUD_ID is set"
          fi

      - run: npm ci --legacy-peer-deps

      - run: npx nx run-many -t build

      - run: npx nx run-many -t lint test build

      - run: npx nx-cloud fix-ci
        if: always()
